mongock:
    change-logs-scan-package:
        - by.zmitser.webapp.reactivities.config
    runner-type: applicationrunner
logging:
    level:
        root: DEBUG
        by.zmitser.webapp.reactivities: DEBUG